"""
Reporter module for AuditAgent.
Files GitHub issues for critical/high security findings.
"""
import os
import json
import logging
from typing import Optional, Dict
from github import Github
from github.Issue import Issue

logger = logging.getLogger(__name__)

# Default threshold for filing issues
DEFAULT_THRESHOLD = 1  # File issue if >= 1 critical or high findings


def create_issue_body(report) -> str:
    """
    Create the GitHub issue body from an audit report.
    
    Args:
        report: AuditReport object
        
    Returns:
        Formatted markdown body for the issue
    """
    body = f"""## 🔒 Security Audit Report

**Repository:** {report.repo_name}
**Audit Timestamp:** {report.timestamp}
**Audit Hash:** `{report.audit_hash}`

---

### Summary

{report.summary}

---

### Severity Breakdown

| Severity | Count |
|----------|-------|
| Critical | {report.severity_breakdown.get('critical', 0)} |
| High | {report.severity_breakdown.get('high', 0)} |
| Medium | {report.severity_breakdown.get('medium', 0)} |
| Low | {report.severity_breakdown.get('low', 0)} |
| Informational | {report.severity_breakdown.get('informational', 0)} |

---

### Detailed Findings

"""
    
    # Group findings by severity
    severity_order = ["critical", "high", "medium", "low", "informational"]
    
    for severity in severity_order:
        severity_findings = [f for f in report.findings if f.get("severity", "").lower() == severity]
        
        if not severity_findings:
            continue
            
        emoji = {
            "critical": "🚨",
            "high": "⚠️", 
            "medium": "⚡",
            "low": "📝",
            "informational": "ℹ️"
        }.get(severity, "•")
        
        body += f"#### {emoji} {severity.upper()} Severity\n\n"
        
        for i, finding in enumerate(severity_findings, 1):
            body += f"**{i}. {finding.get('title', 'Untitled')}**\n\n"
            body += f"- **Description:** {finding.get('description', 'N/A')}\n"
            body += f"- **Impact:** {finding.get('impact', 'N/A')}\n"
            body += f"- **Location:** {finding.get('location', 'N/A')}\n"
            
            if finding.get("recommendation"):
                body += f"- **Recommendation:** {finding.get('recommendation')}\n"
            
            body += "\n"
    
    body += """---

*This issue was automatically generated by AuditAgent. 
If you believe this is a false positive, please let us know!*
"""
    
    return body


def file_github_issue(
    token: str,
    repo_name: str,
    report,
    threshold: int = DEFAULT_THRESHOLD
) -> Optional[str]:
    """
    File a GitHub issue if severity threshold is met.
    
    Args:
        token: GitHub personal access token
        repo_name: Full repo name (e.g., "owner/repo")
        report: AuditReport object
        threshold: Minimum critical+high findings to trigger issue
        
    Returns:
        Issue URL if created, None otherwise
    """
    # Check threshold
    critical_high_count = report.critical_count + report.high_count
    
    if critical_high_count < threshold:
        logger.info(f"Threshold not met ({critical_high_count} < {threshold}). Skipping issue.")
        return None
    
    g = Github(token)
    
    try:
        repo = g.get_repo(repo_name)
        
        # Check if issue already exists for this audit
        issues = repo.get_issues(state="open")
        audit_hash = report.audit_hash
        
        for issue in issues:
            if audit_hash in issue.body:
                logger.info(f"Issue already exists for audit {audit_hash}")
                return issue.html_url
        
        # Create issue title
        title = f"[Security Audit] {report.repo_name} - {critical_high_count} Critical/High Findings"
        
        # Create issue body
        body = create_issue_body(report)
        
        # File the issue
        issue = repo.create_issue(
            title=title,
            body=body,
            labels=["security", "audit", "automated"]
        )
        
        logger.info(f"Created GitHub issue #{issue.number} for {repo_name}")
        return issue.html_url
        
    except Exception as e:
        logger.error(f"Failed to create GitHub issue: {e}")
        raise


def report_findings(
    token: str,
    repo_name: str,
    report,
    threshold: int = DEFAULT_THRESHOLD
) -> Optional[str]:
    """
    Main entry point for reporting findings.
    
    Args:
        token: GitHub personal access token
        repo_name: Full repo name (e.g., "owner/repo") 
        report: AuditReport object
        threshold: Minimum critical+high findings to trigger issue
        
    Returns:
        Issue URL if created, None otherwise
    """
    if not token:
        raise ValueError("GitHub token is required")
    
    if not report.has_critical_or_high:
        logger.info(f"No critical or high findings for {repo_name}. Skipping issue.")
        return None
    
    return file_github_issue(token, repo_name, report, threshold)


if __name__ == "__main__":
    # Test reporting
    logging.basicConfig(level=logging.INFO)
    
    # This would require a real token and report
    print("Reporter module loaded. Use report_findings() to file issues.")
